[build-system]
requires = ["maturin>=1.7,<2"]
build-backend = "maturin"

[project]
name = "rsloop-rust-proxychecker"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "rsloop>=0.1.56",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "rsloop_rust_proxychecker"

[dependency-groups]
dev = [
    "ruff>=0.15.8",
]
